### ISSUE TITLE
Slow first login; why 504 == note is empty?

### ISSUE THREAD

**Issue by DaWe35** [kwypchlo/skydb-example#1]
Hi!

When I enter a new user+pass combo, the note tries to fetch my note from the registry. Because it is a new user, the given registry does not exist. The registry request will throw a 504 error after some time, but it is not really ideal to wait a minute to be able to create a note.

Anyway, why a not-existing registry trows 504 and why not 404?

**Comment by peterjan** [comment]
I can answer this. 

I made a (last-minute edit) mistake in the timeout function, which I have fixed in the meantime. The intention was for a lookup to time out after two seconds. The reason you are seeing a 504 is actually that Nginx gives up on it after 60 seconds I think, the actual request goes on for a total of 5 minutes I believe. A new library should have been published by now fixing the timeout.

A non-existing entry _will_ throw a 404. It will however do so after a very long period of time, which is definitely not ideal.

**Comment by DaWe35** [comment]
> 
> 
> I can answer this.
> 
> I made a (last-minute edit) mistake in the timeout function, which I have fixed in the meantime. The intention was for a lookup to time out after two seconds. The reason you are seeing a 504 is actually that Nginx gives up on it after 60 seconds I think, the actual request goes on for a total of 5 minutes I believe. A new library should have been published by now fixing the timeout.
> 
> A non-existing entry _will_ throw a 404. It will however do so after a very long period of time, which is definitely not ideal.

Thank you for your answer. As I'm working on Sky ID (a global auth system), it was very helpful and I'll implement the login/registration thing separately, so we don't need to wait for 404 (only in a few cases)

Feel to free to close!
